on: [push]

name: CI

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: linuxbrew/brew
    steps:
      - uses: actions/checkout@master
      - name: add
        run: |
          brew tap orf/homebrew-brew file://.
          brew update
      - name: install
        run: |
          brew install git-workspace
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: add
        shell: bash
        run: |
          brew tap orf/homebrew-brew file://.
          brew update
      - name: install
        shell: bash
        run: |
          brew install git-workspace
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Audit
        shell: bash
        run: |
          brew audit --strict *.rb
      - name: Update
        shell: bash
        run: |
          brew tap local/local file://$(pwd)
      - name: Install
        shell: bash
        run: |
          brew install git-workspace
