on: [push]

name: CI

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Audit
        shell: bash
        run: |
          brew audit --strict *.rb
      - name: Update
        shell: bash
        run: |
          brew tap local/local file://$(pwd)
